"""add user

Revision ID: 6024a3aa51dd
Revises: 7cd60eae46a8
Create Date: 2025-11-26 09:53:18.228800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6024a3aa51dd'
down_revision: Union[str, Sequence[str], None] = '7cd60eae46a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_email_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_phone_key'), 'contacts', type_='unique')
    op.create_unique_constraint('uix_email_phone_userid', 'contacts', ['email', 'phone', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_email_phone_userid', 'contacts', type_='unique')
    op.create_unique_constraint(op.f('contacts_phone_key'), 'contacts', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_email_key'), 'contacts', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
